spring.application.name=transaction-service

# Continuing your port map: user=8082, wallet=8083, transaction=8084
server.port=8084

# ---- H2 Database ----
# Transaction service has its OWN database ? stores transaction history
spring.datasource.url=jdbc:h2:mem:transactiondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---- Eureka ----
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ---- Logging ----
logging.level.root=INFO
logging.level.com.sterling.transaction=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.file.name=logs/transaction-service.log

# ---- Actuator ----
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ---- RABBITMQ CONNECTION ----
# Where RabbitMQ broker is running
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ---- QUEUE AND EXCHANGE NAMES ----
# These are just string names. RabbitMQ uses them to identify
# queues and exchanges. Both services MUST use identical names.

# The exchange ? acts like a post office router
rabbitmq.exchange=sterling.exchange

# Queue where Transaction Service sends wallet update messages TO Wallet Service
rabbitmq.queue.wallet-update=wallet.update.queue

# Queue where Wallet Service sends acknowledgements BACK to Transaction Service
rabbitmq.queue.ack=ack.queue

# Routing keys ? used by exchange to decide which queue gets the message
rabbitmq.routing-key.wallet-update=wallet.update
rabbitmq.routing-key.ack=ack.response

# ---- BACKLOG PROCESSOR ----
# How often BacklogProcessor checks for PENDING outbox rows (milliseconds)
# 5000 = every 5 seconds
rabbitmq.backlog.interval=5000

# ---- Eureka Instance Stability (local dev) ----
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.non-secure-port=${server.port}

# JWT validation
jwt.secret=sterlingEwalletSuperSecretKey2024VeryLongSecretForSecurity