spring.application.name=transaction-service

# Continuing your port map: user=8082, wallet=8083, transaction=8084
server.port=8084

# ---- H2 Database ----
# Transaction service has its OWN database ? stores transaction history
spring.datasource.url=jdbc:h2:mem:transactiondb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---- Eureka ----
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ---- Logging ----
logging.level.root=INFO
logging.level.com.sterling.transaction=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.file.name=logs/transaction-service.log

# ---- Actuator ----
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always