spring.application.name=wallet-service

# Your port map has user-service on 8082, so wallet goes to 8083
server.port=8083

# ---- H2 Database ----
# Separate DB from user-service ? each service owns its own data
spring.datasource.url=jdbc:h2:mem:walletdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ---- Eureka ----
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ---- Logging ----
logging.level.root=INFO
logging.level.com.sterling.wallet=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.file.name=logs/wallet-service.log

# ---- Actuator ----
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ---- RABBITMQ CONNECTION ----
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ---- QUEUE AND EXCHANGE NAMES ----
# Must be IDENTICAL to transaction-service properties
rabbitmq.exchange=sterling.exchange
rabbitmq.queue.wallet-update=wallet.update.queue
rabbitmq.queue.ack=ack.queue
rabbitmq.routing-key.wallet-update=wallet.update
rabbitmq.routing-key.ack=ack.response

# ---- Eureka Instance Stability (local dev) ----
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.non-secure-port=${server.port}

# JWT validation
jwt.secret=sterlingEwalletSuperSecretKey2024VeryLongSecretForSecurity